# Generated by Django 2.1.3 on 2018-11-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='подтверждён'),
        ),
    ]
