# Generated by Django 2.1.3 on 2018-11-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_main_bot', models.TextField(blank=True, verbose_name='текст на главной внизу')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('title_page', models.CharField(blank=True, max_length=140, verbose_name='заголовок страницы')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('yandex_verification', models.CharField(blank=True, max_length=100, verbose_name='Yandex Verification')),
                ('yml_name', models.CharField(max_length=250, verbose_name='YML: name')),
                ('yml_email', models.EmailField(max_length=254, verbose_name='YML: email')),
                ('yml_company', models.CharField(max_length=250, verbose_name='YML: company')),
                ('title_blog', models.CharField(blank=True, max_length=140, verbose_name='заголовок блога')),
                ('facebook_app_id', models.CharField(blank=True, max_length=100, verbose_name='FaceBook App ID')),
                ('afrek_id', models.CharField(blank=True, max_length=100, verbose_name='Партнёрка afrek.ru')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Config', verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'менеджер',
                'verbose_name_plural': 'менеджеры',
            },
        ),
    ]
