# Generated by Django 2.1.3 on 2018-11-08 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован')], default=1, verbose_name='Статус')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ('-publish_date',),
            },
        ),
    ]
