# Generated by Django 2.1.3 on 2018-11-08 09:36

from django.db import migrations, models
import django.db.models.deletion
import polymorphic.showfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'банеры',
                'ordering': ('sort',),
            },
            bases=(polymorphic.showfields.ShowFieldContent, models.Model),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banners.Banner')),
                ('template', models.CharField(choices=[('banners/image/default.html', 'картинка по умолчанию')], default='banners/image/default.html', max_length=80, verbose_name='шаблон')),
                ('image', models.ImageField(upload_to='uploads/banners/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'банер с картинкой',
                'verbose_name_plural': 'банеры с картинкой',
            },
            bases=('banners.banner',),
        ),
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banners.Banner')),
                ('template', models.CharField(choices=[('banners/product/default.html', 'Товар по умолчанию')], default='banners/product/default.html', max_length=80, verbose_name='шаблон')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'банер с товаром',
                'verbose_name_plural': 'банеры с товаром',
            },
            bases=('banners.banner',),
        ),
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banners.Banner')),
                ('template', models.CharField(choices=[('banners/text/default.html', 'Текст по умолчанию')], default='banners/text/default.html', max_length=80, verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'банер с текстом',
                'verbose_name_plural': 'банеры с текстом',
            },
            bases=('banners.banner',),
        ),
        migrations.AddField(
            model_name='banner',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_banners.banner_set+', to='contenttypes.ContentType'),
        ),
    ]
