# Generated by Django 2.1.3 on 2018-11-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='вкл/выкл')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['sort'],
            },
            bases=('flatpages.flatpage', models.Model),
        ),
    ]
