# Generated by Django 2.1.3 on 2018-11-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='город')),
                ('slug', models.SlugField(verbose_name='метка')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='наименование')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='dealers.City', verbose_name='город')),
            ],
            options={
                'verbose_name': 'диллер',
                'verbose_name_plural': 'диллеры',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='наименование')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адрес')),
                ('metro', models.CharField(blank=True, max_length=80, verbose_name='метро')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='телефон')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='dealers.Dealer', verbose_name='диллер')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'ordering': ['dealer'],
            },
        ),
    ]
